@BaseUrl = {{$dotenv BASE_URL}}

### Check if is alive
GET {{BaseUrl}}


@Input = me fale todas as informacoes do novo empreendimento olympic que voce possui

### Send a message
POST {{BaseUrl}}/chat

{
    "input": "{{Input}}",
    "session_id": "3",
    "user_name": "Nicolas"
}