@BaseUrl = {{$dotenv BASE_URL}}

@test-message = queria saber mais sobre o free

### Send a test WhatsApp message (no signature required)
POST {{BaseUrl}}/test
Content-Type: application/json

{
  "object": "message",
  "entry": [
    {
        "id": "test_id",
        "changes": [
          {
              "value": {
                "contacts": [
                    {
                      "profile": {
                          "name": "Test User"
                      },
                      "sender_phone_number": "123"
                    }
                ],
                "messages": [
                    {
                      "text": {
                          "body": "{{test-message}}",
                          "id": "123"
                      },
                      "id": "123"
                    }
                ]
              }
          }
        ]
    }
  ]
}
